version: '3'
services:
  mongodb:
    image: mongo:3.2
    volumes:
    - ${PWD}/mgodb:/data/db
    restart: always
  elasticsearch:
    image: deepzz0/elasticsearch:2.4.1
    volumes:
    - ${PWD}/esdata:/usr/share/elasticsearch/data
    restart: always
  eiblog:
    image: deepzz0/eiblog:latest
    volumes:
    - ${PWD}/conf:/app/conf
    extra_hosts:
    - "disqus.com:151.101.192.134"
    - "deepzz.disqus.com:151.101.192.134"
    links:
    - elasticsearch
    - mongodb
    environment:
    - RUN_MODE=prod
    ports:
    - 80:9000
    restart: always
  backup:
    image: deepzz0/backup:latest
    #command: ./backend --restore true
    volumes:
    - ${PWD}/conf:/app/conf
    links:
    - mongodb
    restart: always
